---
config:
  theme: mc
  look: classic
---

flowchart TD
    0A(2022年汤加火山喷发扰动大气)
    0A-->A1
    0A-->A2
    A1(不同纬度流星雷达) -->|获得原始观测数据| B(数据分析)
    A2(WACCM-X模式) -->|假设合适初始扰动| B1(模式运行)
    B --> C11(反演风场)
    B --> C12(反演温度)
    B --> C13(反演密度)
    %% B --> C4(不同纬度流星雷达获得数据)
    B1 --> C21(模拟风场)
    B1 --> C22(模拟温度)
    B1 --> C23(模拟密度)
    %% B --> C4(不同纬度流星雷达获得数据)
    C11 -->D1(对比分析)
    C12 -->D2(对比分析)
    C13 -->D3(对比分析)

    C21 -->D1
    C22 -->D2
    C23 -->D3

    D1 -->E1[得出结论]
    D2 -->E1
    D3 -->E1